# Generated by Django 5.2.5 on 2026-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
        ('wardrobe', '0002_wardrobeitem_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(related_name='outfits', to='wardrobe.wardrobeitem'),
        ),
        migrations.DeleteModel(
            name='OutfitItem',
        ),
    ]
