# Generated by Django 6.0.5 on 2026-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfit_items_delete_outfititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
