# Generated by Django 5.2.5 on 2026-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
