# Generated by Django 6.0.5 on 2026-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_wardrobeitem_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('autumn', 'Autumn'), ('spring', 'Spring')], max_length=20, null=True),
        ),
    ]
